version: "3.4"
services:
  # mysql:
  #   container_name: debezium-mysql
  #   image: debezium/example-mysql:1.8
  #   ports:
  #     - 3306:3306
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=debezium
  #     - MYSQL_USER=mysqluser
  #     - MYSQL_PASSWORD=mysqlpw
  #   volumes:
  #     - ./debezium-server/mysql/data:/var/lib/mysql
  #     - ./debezium-server/mysql/logs:/var/log/mysql
  #   cap_add:
  #     - SYS_NICE
  mongodb:
    image: quay.io/debezium/example-mongodb:${DEBEZIUM_VERSION}
    container_name: debezium-mongodb
    ports:
      - 27017:27017
    environment:
      - MONGODB_USER=debezium
      - MONGODB_PASSWORD=dbz
