version: '2'
services:
  mysql:
    container_name: debezium-mysql
    image: debezium/example-mysql:1.8
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=debezium
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
    volumes:
      - ./debezium-server/mysql/data:/var/lib/mysql
      - ./debezium-server/mysql/logs:/var/log/mysql
    cap_add:
      - SYS_NICE
  debezium-server:
    container_name: debezium-server
    image: debezium/server:latest
    ports:
      - 8080:8080
    volumes:
      - ./debezium-server/conf:/debezium/conf
      # - ./data:/debezium/data
      - ./debezium-server/secret.json:/debezium/secret.json
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/debezium/secret.json
