name: golang_ci
on: [pull_request]
jobs:
  build:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: set up
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
      - name: checkout
        uses: actions/checkout@v1
      - name: cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
        id: cache
      - name: download modules
        if: steps.cache.outputs.cache-hit != 'true'
        run: go mod download
      - name: test
        run: go test ./... -race
